Issue-947 : Add support for vulnerability tags
DependencyTrack/hyades-frontend pull request #45
Opened 2024-04-19 16:56 UTC by sahibamittal

### Description

Add support for vulnerability tags in frontend.

### Addressed Issue

https://github.com/DependencyTrack/hyades/issues/947

### Checklist

- [ ] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/hyades/blob/main/CONTRIBUTING.md#pull-requests)
- [ ] This PR fixes a defect, and I have provided tests to verify that the fix is effective
- [ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended

2024-04-23 14:01 UTC, sahibamittal commented
1. Tags on vulnerability list page
<img width="1512" alt="Screenshot 2024-04-23 at 14 58 13" src="https://github.com/DependencyTrack/hyades-frontend/assets/5709882/fe331424-2629-4f13-8362-16bd7c1898bf">

2. Tag management for internal vulnerability
<img width="1123" alt="Screenshot 2024-04-23 at 14 59 40" src="https://github.com/DependencyTrack/hyades-frontend/assets/5709882/0bbf1d4d-5a65-4e66-bedf-aeb77685d214">

3. Tag management for non-internal vulnerability
<img width="1123" alt="Screenshot 2024-04-23 at 14 59 19" src="https://github.com/DependencyTrack/hyades-frontend/assets/5709882/aa98dc8b-4536-404b-beea-b78a0068373e">

2024-04-24 11:40 UTC, nscuro requested changes

2024-04-24 11:40 UTC, nscuro commented on src/views/portfolio/vulnerabilities/VulnerabilityDetailsModal.vue
> +  <b-modal id="vulnerabilityDetailsModal" size="xl" @show="initializeTags" hide-header-close :title="$t('message.vulnerability_details')">
Does this not break existing behavior?

2024-04-24 11:40 UTC, nscuro commented on src/views/portfolio/vulnerabilities/VulnerabilityDetailsModal.vue
> +    updateVulnerabilityTags: function() {
See https://github.com/DependencyTrack/hyades-apiserver/pull/654#discussion_r1577725710

2024-04-26 12:12 UTC, nscuro approved these changes

2024-04-26 12:13 UTC, merged